name: Build Calculator APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        target: default
        arch: x86_64
    
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
    
    - name: Install Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.24.1
    
    - name: Build APK with specific settings
      run: |
        export JAVA_HOME=$JAVA_HOME_17_X64
        export ANDROID_HOME=$ANDROID_HOME
        flet build apk \
          --verbose \
          --build-number 1 \
          --build-version 1.0.0
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: dist/*.apk
        retention-days: 30
        
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          *.log
          .flet/
        retention-days: 7
