name: Build Calculator APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Set up Flutter (older stable version)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'
        channel: 'stable'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Accept Android licenses
      run: yes | flutter doctor --android-licenses
    
    - name: Install older Flet version
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.23.2
    
    - name: Create simple test app
      run: |
        cat > main.py << 'EOF'
        import flet as ft
        
        def main(page: ft.Page):
            page.title = "Hello World"
            page.add(ft.Text("Hello, World!"))
        
        if __name__ == "__main__":
            ft.app(target=main)
        EOF
    
    - name: Verify Flutter setup
      run: flutter doctor -v
    
    - name: Build APK with compatibility settings
      run: |
        export JAVA_HOME=$JAVA_HOME_11_X64
        flet build apk --no-rich-output
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: dist/*.apk
        retention-days: 30
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          *.log
          .flet/
        retention-days: 7
