name: Build Calculator APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
    
    - name: Install Flutter dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
    
    - name: Install Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet
    
    - name: Build APK
      run: flet build apk --verbose
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: dist/*.apk
        retention-days: 30
